#!/usr/bin/env bash

libdir=$(dirname $(readlink -f ${BASH_SOURCE[0]}))/lib
for lib in $libdir/pre.bash $libdir/*/*.bash; do
    source $lib
done

: {CLIMAH_LIB_CONFIG:=lib/config.develop}
karmah-main "${@}"
